name: Linux Build

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        run: npm run publish
        env:
          CI: true
